name: PR number

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  pr-number:
    name: PR number
    runs-on: ubuntu-latest
    env:
      ref: "prefix-${{ github.event.pull_request.number }}-suffix"
    steps:
      - uses: actions/checkout@v2
      - name: Display
        run: |
          echo "$ref"
